# Generated by Django 4.1.6 on 2023-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0003_usuario_tipo_user_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
