# Generated by Django 4.1.6 on 2023-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0005_rename_descricao_produtos_nome_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=60)),
                ('nome_descricao', models.CharField(max_length=60)),
            ],
        ),
    ]
