# Generated by Django 4.1.6 on 2023-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0006_tabela'),
    ]

    operations = [
        migrations.CreateModel(
            name='preco_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_produto', models.CharField(max_length=10)),
                ('data_preco', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
